name: build docker image

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build Base Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          file: ./Dockerfile-base
          tags: derhenning/sharelatex-base:latest
      - run: docker image ls
      - name: build
        run: docker build -t derhenning/sharelatex:latest .
      - name: push
        run: docker push derhenning/sharelatex:latest
